version: '3.8'

services:
  minio:
    container_name: "minio"
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: minio-root
      MINIO_ROOT_PASSWORD: M@k0nsk@it1os@na
    command: server --console-address ":9001" /data

  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:3.8-management-alpine
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit-bunny
      - RABBITMQ_DEFAULT_PASS=M@k0nsk@it1os@na

  msapi:
    container_name: "msapi"
    image: msapi
    ports:
      - '3000:3000'

volumes:
  minio_storage: {}